// Next.js Code Generator
// Генерация TypeScript/React кода из ComponentNode tree

import { Project, SourceFile, Writers } from 'ts-morph';
import { ts } from 'ts-morph'; // For ts.JsxEmit, etc.
import type { ComponentNode, StyleConfig, StyleValue, Project as ProjectType, Page } from '../stores/canvas-store';
import { componentRegistry, getComponentDefinition } from '@/lib/codegen/component-registry';
import { inferSpatialParentage } from './infer-nesting';

// ========================================
// Types
// ========================================

export interface GeneratedFile {
  path: string;
  content: string;
}

export interface DesignSystemTokens {
  colors: Array<{ name: string; hue: number; saturation: number; lightness: number; alpha: number }>;
  spacing: Array<{ name: string; value: number }>;
  typography: Array<{ name: string; family: string; weights: number[]; fallback?: string }>;
}

// ========================================
// Next.js Generator
// ========================================

export class NextJSGenerator {
  private project: Project;
  private usedImports: Map<string, Set<string>> = new Map();
  
  constructor() {
    this.project = new Project({
      compilerOptions: {
        jsx: ts.JsxEmit.ReactJSX,
        target: ts.ScriptTarget.ES2020,
        module: ts.ModuleKind.ESNext,
        moduleResolution: ts.ModuleResolutionKind.NodeJs,
      },
    });
  }
  
  /**
   * Генерация полного Next.js приложения
   */
  generateProject(project: ProjectType, pages: Page[], nodes: Record<string, ComponentNode>, designTokens: DesignSystemTokens): GeneratedFile[] {
    const files: GeneratedFile[] = [];
    
    // 1. Генерация globals.css с CSS Variables
    files.push(this.generateGlobalStyles(designTokens));
    
    // 2. Генерация layout.tsx
    files.push(this.generateLayout(project));
    
    // 3. Генерация страниц
    for (const page of pages) {
      const pageNodes = Object.values(nodes).filter(n => n.pageId === page.id);
      files.push(this.generatePage(page, pageNodes));
    }
    
    // 4. Генерация runtime bridge для workflow
    files.push(this.generateRuntimeBridge());
    
    return files;
  }
  
  /**
   * Генерация CSS с Design Tokens
   */
  private generateGlobalStyles(tokens: DesignSystemTokens): GeneratedFile {
    const colorVars = tokens.colors.map(c => {
      const hsl = `hsla(${c.hue} ${c.saturation}% ${c.lightness}% / ${c.alpha})`;
      return `  --color-${c.name}: ${hsl};`;
    }).join('\n');
    
    const spacingVars = tokens.spacing.map(s => {
      return `  --spacing-${s.name}: ${s.value}rem;`;
    }).join('\n');
    
    const typographyVars = tokens.typography.map(t => {
      return `  --font-${t.name}: ${t.family}, ${t.fallback || 'system-ui, sans-serif'};`;
    }).join('\n');
    
    const content = `@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  :root {
${colorVars}
    
${spacingVars}
    
${typographyVars}
  }
}

@layer base {
  * {
    @apply border-border;
  }
  body {
    @apply bg-background text-foreground;
  }
}
`;
    
    return { path: 'app/globals.css', content };
  }
  
  /**
   * Генерация корневого layout.tsx
   */
  private generateLayout(project: ProjectType): GeneratedFile {
    const file = this.project.createSourceFile('temp-layout.tsx', '', { overwrite: true });
    
    file.addImportDeclaration({
      moduleSpecifier: 'next/font',
      namedImports: ['Inter'],
    });
    
    file.addStatements(`
import type { Metadata } from 'next';
import './globals.css';
import { WorkflowRuntimeProvider } from '@/components/workflow-runtime';

const inter = Inter({ subsets: ['latin', 'cyrillic'] });

export const metadata: Metadata = {
  title: '${project.name}',
  description: 'Generated by Shakel Builder',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WorkflowRuntimeProvider>
          {children}
        </WorkflowRuntimeProvider>
      </body>
    </html>
  );
}
`);
    
    return { path: 'app/layout.tsx', content: file.getFullText() };
  }
  
  /**
   * Генерация страницы
   */
  private generatePage(page: Page, nodes: ComponentNode[]): GeneratedFile {
    this.usedImports.clear();
    
    const file = this.project.createSourceFile(`temp-page-${page.slug}.tsx`, '', { overwrite: true });
    
    // Группируем ноды по parentId
    const nodeTree = this.buildNodeTree(nodes);
    
    // Находим корневые ноды (from the tree, which may have inferred parentage)
    const rootNodes = nodeTree.get(null)?.sort((a, b) => a.order - b.order) ?? [];
    
    // Генерируем JSX для каждого корневого нода
    const rootElements = rootNodes.map(node => this.generateJSXForNode(node, nodeTree));
    
    // Добавляем imports
    this.addImports(file);
    
    // Добавляем runtime imports
    file.addImportDeclaration({
      moduleSpecifier: '@/components/workflow-runtime',
      namedImports: ['useWorkflowRuntime'],
    });
    
    // Генерируем компонент страницы
    const pageContent = `
export default function ${this.pascalCase(page.name)}Page() {
  return (
    <main className="min-h-screen">
${rootElements.join('\n')}
    </main>
  );
}
`;
    
    file.addStatements(pageContent);
    
    return { 
      path: `app/${page.slug === '/' ? 'page' : page.slug + '/page'}.tsx`, 
      content: file.getFullText() 
    };
  }
  
  /**
   * Построение дерева нод
   */
  private buildNodeTree(nodes: ComponentNode[]): Map<string | null, ComponentNode[]> {
    const resolved = inferSpatialParentage(nodes);

    const tree = new Map<string | null, ComponentNode[]>();
    
    for (const node of resolved) {
      const key = node.parentId;
      if (!tree.has(key)) {
        tree.set(key, []);
      }
      tree.get(key)!.push(node);
    }
    
    // Сортируем по order
    for (const [, children] of tree) {
      children.sort((a, b) => a.order - b.order);
    }
    
    return tree;
  }
  
  /**
   * Рекурсивная генерация JSX для ноды
   */
  private generateJSXForNode(node: ComponentNode, tree: Map<string | null, ComponentNode[]>, indent: number = 6): string {
    const def = getComponentDefinition(node.type);
    if (!def) {
      console.warn(`Unknown component type: ${node.type}`);
      return '';
    }
    
    // Отслеживаем импорты
    for (const imp of def.imports) {
      if (!this.usedImports.has(imp)) {
        this.usedImports.set(imp, new Set());
      }
      this.usedImports.get(imp)!.add(def.componentName);
    }
    
    // Генерируем className из стилей
    const className = this.generateClassName(node.styles);
    
    // Генерируем props
    const props = this.serializeProps(node.props, def.props);
    
    // Генерируем event handlers для интеракций
    const eventHandlers = this.generateEventHandlers(node);
    
    // Получаем детей
    const children = tree.get(node.id) || [];
    
    const indentStr = ' '.repeat(indent);
    
    if (children.length === 0) {
      // Self-closing или с текстом
      if (def.type === 'text') {
        const text = (node.props.content as string) || 'Text';
        return `${indentStr}<${def.componentName}${props}${className}${eventHandlers}>${text}</${def.componentName}>`;
      }
      if (def.type === 'button') {
        const text = (node.props.text as string) || 'Button';
        return `${indentStr}<${def.componentName}${props}${className}${eventHandlers}>${text}</${def.componentName}>`;
      }
      if (def.type === 'image') {
        return `${indentStr}<${def.componentName}${props}${className}${eventHandlers} />`;
      }
      return `${indentStr}<${def.componentName}${props}${className}${eventHandlers} />`;
    }
    
    // С детьми
    const childrenJSX = children
      .map(child => this.generateJSXForNode(child, tree, indent + 2))
      .filter(Boolean)
      .join('\n');
    
    return `${indentStr}<${def.componentName}${props}${className}${eventHandlers}>\n${childrenJSX}\n${indentStr}</${def.componentName}>`;
  }
  
  /**
   * Генерация className из стилей
   */
  private generateClassName(styles: StyleConfig): string {
    const classes: string[] = [];
    
    // Конвертируем токены в CSS классы
    for (const [key, value] of Object.entries(styles.base || {})) {
      if (value.type === 'token') {
        // Используем CSS переменные
        // Например: bg-[var(--color-primary)]
        classes.push(`[--${key}:var(--${value.tokenType}-${value.value})]`);
      }
    }
    
    return classes.length > 0 ? ` className="${classes.join(' ')}"` : '';
  }
  
  /**
   * Сериализация props
   */
  private serializeProps(props: Record<string, unknown>, propSchema: any[]): string {
    const entries: string[] = [];
    
    for (const [key, value] of Object.entries(props)) {
      if (value === undefined || value === null) continue;
      if (typeof value === 'boolean') {
        if (value) entries.push(key); // boolean true как флаг
      } else if (typeof value === 'number') {
        entries.push(`${key}={${value}}`);
      } else if (typeof value === 'string') {
        entries.push(`${key}="${value}"`);
      } else {
        entries.push(`${key}={${JSON.stringify(value)}}`);
      }
    }
    
    return entries.length > 0 ? ' ' + entries.join(' ') : '';
  }
  
  /**
   * Генерация обработчиков событий для интеракций
   */
  private generateEventHandlers(node: ComponentNode): string {
    if (node.interactions.length === 0) return '';
    
    const handlers: string[] = [];
    
    for (const interaction of node.interactions) {
      if (interaction.trigger === 'onClick') {
        handlers.push(`onClick={handleInteraction_${interaction.id}}`);
      } else if (interaction.trigger === 'onSubmit') {
        handlers.push(`onSubmit={handleInteraction_${interaction.id}}`);
      }
    }
    
    return handlers.length > 0 ? ' ' + handlers.join(' ') : '';
  }
  
  /**
   * Добавление импортов в файл
   */
  private addImports(file: SourceFile): void {
    for (const [module, components] of this.usedImports) {
      file.addImportDeclaration({
        moduleSpecifier: module,
        namedImports: Array.from(components),
      });
    }
  }
  
  /**
   * Генерация runtime bridge для workflow
   */
  private generateRuntimeBridge(): GeneratedFile {
    const content = `'use client';

import { createContext, useContext, useCallback, ReactNode } from 'react';

interface WorkflowRuntimeContext {
  trigger: (workflowId: string, input: Record<string, unknown>) => Promise<void>;
  navigate: (url: string) => void;
  openModal: (modalId: string) => void;
}

const Context = createContext<WorkflowRuntimeContext | null>(null);

export function WorkflowRuntimeProvider({ children }: { children: ReactNode }) {
  const trigger = useCallback(async (workflowId: string, input: Record<string, unknown>) => {
    const response = await fetch('/api/workflows/trigger', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ workflowId, input }),
    });
    
    if (!response.ok) {
      throw new Error('Failed to trigger workflow');
    }
  }, []);
  
  const navigate = useCallback((url: string) => {
    window.location.href = url;
  }, []);
  
  const openModal = useCallback((modalId: string) => {
    // Modal logic
    console.log('Open modal:', modalId);
  }, []);
  
  return (
    <Context.Provider value={{ trigger, navigate, openModal }}>
      {children}
    </Context.Provider>
  );
}

export function useWorkflowRuntime() {
  const context = useContext(Context);
  if (!context) {
    throw new Error('useWorkflowRuntime must be used within WorkflowRuntimeProvider');
  }
  return context;
}
`;
    
    return { path: 'components/workflow-runtime.tsx', content };
  }
  
  /**
   * Вспомогательная функция: kebab-case → PascalCase
   */
  private pascalCase(str: string): string {
    return str
      .replace(/[-_]/g, ' ')
      .replace(/(?:^|\\s|\\W)\\w/g, (match) => match.toUpperCase())
      .replace(/\\s/g, '');
  }
}

// ========================================
// NestJS Generator (для ботов)
// ========================================

export class NestJSBotGenerator {
  generateBot(project: ProjectType, pages: Page[], nodes: Record<string, ComponentNode>): GeneratedFile[] {
    const files: GeneratedFile[] = [];
    
    // 1. Генерация модуля бота
    files.push(this.generateBotModule(project));
    
    // 2. Генерация хендлеров для каждой страницы (экрана бота)
    for (const page of pages) {
      const pageNodes = Object.values(nodes).filter(n => n.pageId === page.id);
      files.push(this.generateHandler(page, pageNodes));
    }
    
    // 3. Генерация сервиса
    files.push(this.generateBotService(project));
    
    // 4. Генерация клавиатур
    files.push(this.generateKeyboards(pages, nodes));
    
    return files;
  }
  
  private generateBotModule(project: ProjectType): GeneratedFile {
    const content = `import { Module } from '@nestjs/common';
import { BotService } from './bot.service';
${(project as any).pages?.map((p: any) => `import { ${this.pascalCase(p.name)}Handler } from './handlers/${this.kebabCase(p.name)}.handler';`).join('\n') || ''}

@Module({
  providers: [
    BotService,
    ${(project as any).pages?.map((p: any) => `${this.pascalCase(p.name)}Handler,`).join('\n    ') || ''}
  ],
})
export class BotModule {}
`;
    
    return { path: 'src/bot/bot.module.ts', content };
  }
  
  private generateHandler(page: Page, nodes: ComponentNode[]): GeneratedFile {
    // Находим текстовые ноды и кнопки
    const textNodes = nodes.filter(n => n.type === 'telegramText');
    const keyboardNodes = nodes.filter(n => n.type === 'telegramKeyboard');
    
    const handlerName = this.pascalCase(page.name);
    
    const content = `import { Injectable } from '@nestjs/common';
import { Ctx, Hears, Update } from 'nestjs-telegraf';
import { Context } from 'telegraf';
import { BotService } from '../bot.service';
import { getKeyboard } from '../keyboards';

@Update()
@Injectable()
export class ${handlerName}Handler {
  constructor(private readonly botService: BotService) {}

  @Hears('${page.isEntry ? '/start' : page.name}')
  async handle${handlerName}(@Ctx() ctx: Context) {
    ${textNodes.map(n => `
    await ctx.reply('${(n.props.content as string)?.replace(/'/g, "\\'") || 'Hello'}', {
      parse_mode: '${n.props.parseMode || 'HTML'}',
      ...getKeyboard('${page.id}'),
    });
    `).join('\n')}
  }
}
`;
    
    return { path: `src/bot/handlers/${this.kebabCase(page.name)}.handler.ts`, content };
  }
  
  private generateBotService(project: ProjectType): GeneratedFile {
    const content = `import { Injectable } from '@nestjs/common';
import { InjectBot } from 'nestjs-telegraf';
import { Telegraf } from 'telegraf';
import { Context } from 'telegraf';

@Injectable()
export class BotService {
  constructor(@InjectBot() private bot: Telegraf<Context>) {}
  
  async sendMessage(chatId: string, text: string, options?: any) {
    return this.bot.telegram.sendMessage(chatId, text, options);
  }
}
`;
    
    return { path: 'src/bot/bot.service.ts', content };
  }
  
  private generateKeyboards(pages: Page[], nodes: Record<string, ComponentNode>): GeneratedFile {
    // Генерация клавиатур для каждой страницы
    const keyboards: string[] = [];
    
    for (const page of pages) {
      const pageNodes = Object.values(nodes).filter(n => n.pageId === page.id);
      const keyboardNode = pageNodes.find(n => n.type === 'telegramKeyboard');
      
      if (keyboardNode) {
        const buttonNodes = pageNodes.filter(n => n.parentId === keyboardNode.id && n.type === 'telegramKeyboardButton');
        
        const buttons = buttonNodes.map(btn => ({
          text: btn.props.text as string,
          request_contact: btn.props.requestContact as boolean,
          request_location: btn.props.requestLocation as boolean,
        }));
        
        keyboards.push(`
  '${page.id}': {
    keyboard: [
      ${JSON.stringify(buttons)}
    ],
    resize_keyboard: ${keyboardNode.props.resize ?? true},
    one_time_keyboard: ${keyboardNode.props.oneTime ?? false},
  },`);
      }
    }
    
    const content = `import { Markup } from 'telegraf';

const keyboards = {${keyboards.join('\n')}
};

export function getKeyboard(pageId: string) {
  const keyboard = keyboards[pageId];
  if (!keyboard) return {};
  
  return Markup.keyboard(keyboard.keyboard)
    .resize(keyboard.resize_keyboard)
    .oneTime(keyboard.one_time_keyboard);
}
`;
    
    return { path: 'src/bot/keyboards/index.ts', content };
  }
  
  private pascalCase(str: string): string {
    return str.replace(/[-_]/g, ' ').replace(/(?:^|\\s)\\w/g, (match) => match.toUpperCase()).replace(/\\s/g, '');
  }
  
  private kebabCase(str: string): string {
    return str.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase().replace(/\\s+/g, '-');
  }
}


